### PR TITLE
1.0/45 ci to GitHub pages

### LINKED ISSUE #45: Set up Travis for CI to release default branch to gh-pages
## Description
Set up travis (or try circle)

## Plan
- [x] config
- [ ] test
- [x] incorporate elm-test and elm-format into CI as per #11 
- [ ] We need tests to pass.

### PR DESCRIPTION
**Pull request by katjam**
Fixes #45

## Description

- Deploys to gh-pages on push of tag

@neontribe/contemplating-action

### CODE REVIEW

**Review by Nikomus — DISMISSED** [review]
🚀 Awesome!

**Comment by Nikomus** [comment]
@katjam One small thing, should we add to the readme about tagging the repo to trigger a deploy to staging?

**Comment by katjam** [comment]
Yes - we should. I will.

**Comment by katjam** [comment]
Added notes in readme

**Review by Nikomus — APPROVED** [review]
Nice, clear docs! 📄 ✔️

**Pull request merged**
