### PR TITLE
Update Google Analytics global site tag (gtag) code

### LINKED ISSUE #197: VVV/EE Generate GA tracking on first page load
## Description
Google analytics are only initialised on update events. This means that the first page load for a new visitor won't be recorded, with tracking starting from after they've navigated to a new page.

## Plan
- [x] Investigate if this is a problem we'd like to fix or not.
- [x] Fix it

## Acceptance Criteria
- [ ] For all brands a GA tracking event is sent on initial page load of home page when the site is visited.
- [ ] Note that it is likely at least one brand has not been updated (see list below)
- [ ] www.youmattertoday.org.uk (Haven)
- [ ] www.contemplatingaction.org.uk
- [ ] neontribe.github.io/ca-hospice-hope & https://www.hopestories.org.uk/
- [ ] neontribe.github.io/ca-seap
- [ ] neontribe.github.io/ca-samaritans

### PR DESCRIPTION
**Pull request by AlinChindea**
Fixes #197 

## Description

- code for the gtag was incomplete - see [documentation](https://developers.google.com/analytics/devguides/collection/gtagjs)
- code needs the config command to initialise and configure settings for a particular product account - see [documentation for details](https://developers.google.com/gtagjs/devguide/configure)
- in this case, the config command tells gtag.js to initiate a pageview hit and send it to GA
@neontribe/contemplating-action

### CODE REVIEW

**Review by katjam — APPROVED** [review]
Looks good. Can you also please update the other 3 `ca-` repos?

**Comment by AlinChindea** [comment]
> Looks good. Can you also please update the other 3 `ca-` repos?

@katjam do we use the same <TARGET_ID> for all 4 web apps? if we consider these as 4 different products, we probably need a different id for each.

**Comment by katjam** [comment]
Yes - each brand will need its own id. We add a xxxxxxx or 000000 type one for a placeholder where we have no number yet. There should be different tickets about that.

**Comment by AlinChindea** [comment]
Ok then. I will merge this PR.

**Pull request merged**
